const simulateCMS_Site = {
  "basic-r1": "Helllloooooookdjfbsdijfbdsjifbdsfhbd sfuHelllloooooookdjfbsdijfbdsjifbHelllloooooookdjfbsdijfbdsji fbHelllloooooookdjfbsdijfbdsjifbHelllloooo oookdjfbsdijfbdsjifbHelllloooooookdjfbsdijfbdsjifbHelllloooooookdjfbsdijf bdsjifbHelllloooooookdjfbsdijfbdsjifbHelllloooooookdjfbsdijfbdsjifbHelllloooooookdjfbsdijfbdsjifbHe lllloooooookdjfbsdijfbdsjifbHelllloooooookdjfbs dijfbdsjifbHelllloooooookdjfbsdijfbdsjifbHellllooooo ookdjfbsdijfbdsjifbHelllloooooookdjfbsdijfbdsjifbHelllloooooookdjfbsdijfbdsjifbHelllloooooookdjfbsdijfbdsjifb HelllloooooookdjfbsdijfbdsjifbHelllloooooookdjfbsdijfbdsjifbHelllloooooookdjfbsdijfbdsjifbHelllloooooookdjfbsdijfbdsjifbHellll oooooookdjfbsdijfbdsjifbHelllloooooookdjfbsdijfbdsjifbHelllloooooookdjfbsdijfbdsjifbHellll oooooookdjfbsdijfbdsjifbHelllloooooookdjfbsdijfbdsjifbHelllloooooookdjfbsdijfbdsjifbHelllloooooookdjfbsdijfbdsjifbHelllloooooookdjfbsdijfbdsjifbHelllloooooookdjfbsdijfbdsjifbHel llloooooookdjfbsdijfbdsjifbHelll loooooookdjfbsdijfbdsjifbHelllloooooookdjfbsdijfbdsjifbHelllloooooookdjfbsdijfbdsjifb",
  "dual-r2": "HERE IM DUAL"
}

export default (state = simulateCMS_Site, action) => {

  return state
}